/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.manufacturerrole;

import business.enterprise.Enterprise;
import business.organization.InventoryOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.InventoryWorkRequest;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Pooja
 */
public class InventoryRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ManufactureOrganization organization;

    InventoryRequestsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = (ManufactureOrganization) organization;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        itemCountJTextField = new javax.swing.JTextField();
        requestInventoryJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        itemNameJTextField1 = new javax.swing.JTextField();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 50));

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel1.setText("Item Count");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        itemCountJTextField.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        itemCountJTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(itemCountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 115, -1));

        requestInventoryJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestInventoryJButton.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        requestInventoryJButton.setText("Send Inventory Request");
        requestInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestInventoryJButtonActionPerformed(evt);
            }
        });
        add(requestInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 250, 50));

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel2.setText("Item Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        itemNameJTextField1.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        itemNameJTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(itemNameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 115, -1));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 230, 26));

        valueLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 210, 26));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("REQUESTING INVENTORY");
        jPanel2.add(jTextField1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/manufacturerrole/ccbluebig.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManufacturerWorkRequestsJPanel dwjp = (ManufacturerWorkRequestsJPanel) component;
        dwjp.populateDesignerWorkRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestInventoryJButtonActionPerformed
         
        String itemCount = itemCountJTextField.getText();
        String itemName = itemNameJTextField1.getText();
        InventoryWorkRequest request = new InventoryWorkRequest();
         // validating the fields of the inventory
        if (itemCount.matches("[0-9]+")) {
            request.setItemCount(Integer.parseInt(itemCount));
        } else {
            JOptionPane.showMessageDialog(null, "Item count has to be a number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (itemName.matches("[a-zA-Z]+")) {
            request.setItemName(itemName);
        } else {
            JOptionPane.showMessageDialog(null, "Item name has to be a string", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setManufacturerSenderInv(userAccount);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);

        }
        JOptionPane.showMessageDialog(null, "Inventory Request sent to Inventory Staff", "Info", JOptionPane.INFORMATION_MESSAGE);
        itemCountJTextField.setText("");
        itemNameJTextField1.setText("");
    }//GEN-LAST:event_requestInventoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JTextField itemCountJTextField;
    private javax.swing.JTextField itemNameJTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton requestInventoryJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
