/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.manufacturerrole;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shreya
 */
public class ManufacturerWorkAreaManangementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerWorkAreaManangementJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ManufactureOrganization organization;
    private UserAccount userAccount;
    private Ecosystem business;

    public ManufacturerWorkAreaManangementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (ManufactureOrganization) organization;
        this.userAccount = account;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizedOrderJButton = new javax.swing.JButton();
        backJButton3 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        customizedOrderJButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customizedOrderJButton.setBackground(new java.awt.Color(204, 204, 255));
        customizedOrderJButton.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        customizedOrderJButton.setText("Customised Orders Work Requests");
        customizedOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedOrderJButtonActionPerformed(evt);
            }
        });
        add(customizedOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 410, 140));

        backJButton3.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        backJButton3.setText("Back");
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 40));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 87, 26));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 26));

        customizedOrderJButton1.setBackground(new java.awt.Color(204, 204, 255));
        customizedOrderJButton1.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        customizedOrderJButton1.setText("Inventory Work Requests");
        customizedOrderJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedOrderJButton1ActionPerformed(evt);
            }
        });
        add(customizedOrderJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 410, 140));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manufacturer Work Area ");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Management");
        jPanel1.add(jLabel6);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/manufacturerrole/manufacturing.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void customizedOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedOrderJButtonActionPerformed
        // TODO add your handling code here:
        ManufacturerWorkRequestsJPanel manufactureJPanel = new ManufacturerWorkRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanel", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customizedOrderJButtonActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void customizedOrderJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedOrderJButton1ActionPerformed
        RequestsFromInventoryWorkRequestJPanel manufactureJPanel = new RequestsFromInventoryWorkRequestJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanelNew", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customizedOrderJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JButton customizedOrderJButton;
    private javax.swing.JButton customizedOrderJButton1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
