/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pooja
 */
public class CustomerMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private JPanel userProcessContainer;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;

    public CustomerMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(account.getUsername());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizejBtn = new javax.swing.JButton();
        buyAtStorejBtn = new javax.swing.JButton();
        customerOrdersJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        customerTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customizejBtn.setBackground(new java.awt.Color(204, 204, 255));
        customizejBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customizejBtn.setText("CUSTOMIZE YOUR CAR ");
        customizejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizejBtnActionPerformed(evt);
            }
        });
        add(customizejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 370, 230));

        buyAtStorejBtn.setBackground(new java.awt.Color(204, 204, 255));
        buyAtStorejBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        buyAtStorejBtn.setText("BUY AT STORE");
        buyAtStorejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAtStorejBtnActionPerformed(evt);
            }
        });
        add(buyAtStorejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 230, 120));

        customerOrdersJButton.setBackground(new java.awt.Color(204, 204, 255));
        customerOrdersJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customerOrdersJButton.setText("REQUESTED ORDERS");
        customerOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerOrdersJButtonActionPerformed(evt);
            }
        });
        add(customerOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 230, 110));

        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 50));

        customerTextField.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, 30));

        jLabel8.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel8.setText("Hello!");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO THE SHOWROOM!");
        jPanel1.add(jLabel1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/car--v2.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, -1, 290));
    }// </editor-fold>//GEN-END:initComponents


    private void customizejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizejBtnActionPerformed

        // TODO add your handling code here:
        CustomizeJPanel cjp = new CustomizeJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
        userProcessContainer.add("CustomizeJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_customizejBtnActionPerformed

    private void buyAtStorejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAtStorejBtnActionPerformed
        //  TODO add your handling code here:
        BuyAtStoreJPanel cjp = new BuyAtStoreJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
        userProcessContainer.add("BuyAtStoreJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buyAtStorejBtnActionPerformed

    private void customerOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerOrdersJButtonActionPerformed
        //  TODO add your handling code here:
        CustomerOrdersJPanel cjp = new CustomerOrdersJPanel(userProcessContainer, account, customerOrganization, enterprise, business);
        userProcessContainer.add("CustomerOrdersJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_customerOrdersJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton buyAtStorejBtn;
    private javax.swing.JButton customerOrdersJButton;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JButton customizejBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
