/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.person.Person;
import business.role.CustomerRole;
import business.role.Role;
import business.useraccount.UserAccount;
import business.useraccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pooja
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel userProcessContainer;
    UserAccountDirectory userAccountDirectory;

    public SignUpJPanel(JPanel userProcessContainer, UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccountDirectory = userAccountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        verificationLabel = new javax.swing.JLabel();
        verificationLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        usernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 118, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, 20));

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel2.setText("User Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, 20));

        jLabel5.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, 20));

        jLabel6.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("*");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 21, 30));

        jLabel7.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("*");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 21, 20));

        jLabel8.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("*");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 20, 20));

        submitJButton.setBackground(new java.awt.Color(102, 153, 255));
        submitJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, 40));

        backjButton1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backjButton1.setText("Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 40));

        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 118, 27));

        confirmPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 118, 29));

        verificationLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        verificationLabel.setForeground(new java.awt.Color(255, 51, 51));
        add(verificationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 207, 20));

        verificationLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        verificationLabel1.setForeground(new java.awt.Color(255, 51, 51));
        add(verificationLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 207, 20));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel4.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign Up");
        jPanel1.add(jLabel4);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/sign up.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 560, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String username = usernameTextField.getText();
        char[] password = passwordField.getPassword();
        char[] confirmPassword = confirmPasswordField.getPassword();

        String pwd = String.valueOf(password);
        String confirmPwd = String.valueOf(confirmPassword);
        //validations the fields
        int flag = 1;
        if (username.isEmpty() || pwd.isEmpty() || confirmPwd.isEmpty()) {
            verificationLabel.setText("Fields can't be left blank!");
            flag = 0;
        } else if (!pwd.equals(confirmPwd)) {
            verificationLabel1.setText("Passwords don't match");
            flag = 0;
        }
        if (flag == 1) {

            Person emp = new Person();
            emp.setName(usernameTextField.getText());

            UserAccount ua = new UserAccount();
            ua.setEmployee(emp);
            ua.setUsername(username);
            ua.setPassword(pwd);
            Role role = new CustomerRole();

            verificationLabel1.setText("");
            verificationLabel.setText("");
            usernameTextField.setText("");
            passwordField.setText("");
            confirmPasswordField.setText("");

            userAccountDirectory.createUserAccount(username, pwd, emp, role);

            JOptionPane.showMessageDialog(null, username + " " + "user created Successfully! ", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel verificationLabel;
    private javax.swing.JLabel verificationLabel1;
    // End of variables declaration//GEN-END:variables
}
